### ISSUE TITLE
Invalid destruct on valid destruct / assignment with numbers

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#12] opened 2019-03-18 11:40 UTC
Found this cases:

- [x] `let {a,b=0,c:d,e:f=0,[g]:[h]}=0`

- [x] `({a,b=b,a:c,[a]:[d]})=>0;`

- [x] `({a, a:a, a:a=a, [a]:{a}, a:some_call()[a], a:this.a} = 0);`

- [x] `var m = 'foo'; var {[m]:[z]} = {foo:[1]}`

**Comment by pvdz** [comment] 2019-04-13 15:35
Ah this is caused by computed properties. Looks like they are not parsing properly. Nice find! :)

**Comment by pvdz** [comment] 2019-04-13 15:42
Actually, seems to be a combination of the computed key and computed alias

```
var {[a]: [b]} = c // fail
var {[a]: b} = c // pass
var {a: [b]} = c // pass
```

**Comment by pvdz** [comment] 2019-04-13 19:24
All fixed now. Thanks for reporting :)

**Closed by pvdz** 2019-04-13 19:24 UTC
