### ISSUE TITLE
TypeError: Cannot set property '#A' of undefined

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#11] opened 2019-03-18 01:24 UTC
Try to parse `(class A extends B { method() { super() } })` and you get this error message
`TypeError: Cannot set property '#A' of undefined`.

It seem to happen somewhere inside `SCOPE_addBindingAndDedupe`

**Comment by pvdz** [comment] 2019-04-07 15:44
Right. This was caused by scoping making assumptions that do not hold for async in webcompat. Kind of the reason why you'd want to test for all possible worlds, if that was feasible. Which it definitely is not.

Fixed with a simple patch and overhauling the whole scoping to make it more robust across the board.

**Closed** 2019-04-07 19:05 UTC
